### ISSUE TITLE
myblog - `NetworkPolicies` improvements

### ISSUE THREAD

**Issue by mathieu-benoit** [mathieu-benoit/my-kubernetes-deployments#7]
I'm wondering if I could improve the `NetworkPolicies` setup with myblog:

Egress is all open, could I restrict the egress wide open but just for the istio-proxy sidecar which needs this? But maybe not the myblog Pod? Today I use the `app=myblog` selector: https://github.com/mathieu-benoit/my-kubernetes-deployments/blob/main/namespaces/myblog/networkpolicies.yaml#L18

Does this `istio-proxy` sidecar needs this below for example?
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-to-istiod
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: istio-controlplane   # label name for istio-system namespace
    - podSelector:
        matchLabels:
          istio: pilot   # label match for istiod pods
  - ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
```
And what about the fact that it sends trace to Cloud Monitoring/Trace?

Further considerations too, when I will add the `IngressGateway` in front of myblog, should I need to change/restrict the `Ingress` rules like illustrated with [`productpage` in there](https://istio.io/latest/blog/2017/0.1-using-network-policy/)?
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: product-page-ingress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: productpage
  ingress:
  - ports:
    - protocol: TCP
      port: 9080
    from:
    - podSelector:
        matchLabels:
          istio: ingress
```
Like illustrated
